default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS") { 5 } } %>

local: &local
  <<: *default
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *local
  database: <%= ENV.fetch("POSTGRES_DB_DEVELOPMENT", "optimus_development") %>

test:
  <<: *local
  database: <%= ENV.fetch("POSTGRES_DB_TEST", "optimus_test") %>

production:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>
  cache:
    <<: *default
    url: <%= ENV.fetch("CACHE_DATABASE_URL") { ENV.fetch("DATABASE_URL") } %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV.fetch("QUEUE_DATABASE_URL") { ENV.fetch("DATABASE_URL") } %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV.fetch("CABLE_DATABASE_URL") { ENV.fetch("DATABASE_URL") } %>
    migrations_paths: db/cable_migrate
