name: Update Packages

on:
  schedule:
    - cron: '5 12 * * *' # 06:05 CST (UTC-6)
  workflow_dispatch:

jobs:
  update:
    uses: mpimedia/mpi-application-workflows/.github/workflows/update-packages.yml@f00663fa9e97a7dafa18b276a6e483094116b98e # pin to known-good SHA
    secrets: inherit
